---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: httpd-deployment
    labels:
      app: httpd
spec:
replicas: 2
selector:
     app: httpd2
template:
     metadata:
        labels:
            app: httpd2
     spec:
             containers:
                - name: httpd
                  image: saidevops94/repos:latest
             ports:
                - containerPort: 80
