---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: httpd-deployment
    labels:
      app: httpd
spec:
replicas: 2
selector:
   matchLabels:
     app: httpd2
template:
     metadata:
        labels:
            app: httpd2
     spec:
           containers:
                - name: apache2
               image: 
              ports:
                - containerPort: 80
